maximum_name: 50
maximum_email: 255
minium_password: 6
remember_session: "1"
gravatar_size: 50
default_gravatar_size: 80
expired_time: 2 # hours
per_page_users: 10
per_page_microposts: 5
maximum_content_mp: 140
max_picture_size: 5
accept_picture: "image/jpeg,image/gif,image/png"
